{% set name = "wiutils" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wiutils-{{ version }}.tar.gz
  sha256: da5e20af6c82d157c686ba39eaa0a7b56016dc88fc05ab3310449cc166f6ae7f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ffmpeg
    - ffmpeg-python
    - numpy
    - opencv
    - openpyxl
    - pandas
    - pillow
    - python >=3.6

test:
  imports:
    - wiutils
  requires:
    - pip

about:
  home: https://github.com/PEM-Humboldt/wildlife-insights-utils
  summary: Transformation and exploration utilities for information downloaded from Wildlife Insights projects.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marcelovilla
